name: mafortune
description: "Application de gestion financière pour les commerçants du secteur informel au Togo"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.0
  shared_preferences: ^2.2.0
  fl_chart: ^0.68.0          # Pour les graphiques
  syncfusion_flutter_charts: ^24.2.7  # Alternative plus riche (optionnel)
  intl: ^0.19.0
  local_auth: ^2.1.6          # Pour la biométrie
  flutter_secure_storage: ^9.0.0  # Stockage sécurisé du PIN
  image_picker: ^1.0.0
  pdf: ^3.10.7
  printing: ^5.11.1
  
  

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2
  firebase_storage: ^12.3.8
  
  # State Management
  provider: ^6.1.2
  
  # UI
  cupertino_icons: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
 
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logoapp.jpg"
  adaptive_icon_background: "#2E7D32"
  adaptive_icon_foreground: "assets/icon/logoapp.jpg"

flutter:
  uses-material-design: true