name: mafortune
description: "Application de gestion financière pour les commerçants du secteur informel au Togo"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  shared_preferences: ^2.5.5
  fl_chart: ^1.2.0
  syncfusion_flutter_charts: ^33.1.49
  intl: ^0.20.2
  local_auth: ^3.0.1
  flutter_secure_storage: ^10.0.0
  image_picker: ^1.1.0
  pdf: ^3.10.7
  printing: ^5.11.1
  connectivity_plus: ^7.1.1
  sqflite: ^2.4.0
  path_provider: ^2.1.0
  workmanager: ^0.9.0+3
  path: ^1.9.0

  # Firebase
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.3.0

  # State Management
  provider: ^6.1.2

  # UI
  cupertino_icons: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logoapp.jpg"
  adaptive_icon_background: "#2E7D32"
  adaptive_icon_foreground: "assets/icon/logoapp.jpg"

flutter:
  uses-material-design: true