// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Ek7LpvHhZTvMaYx4w5GZV1bNH6zsCZU',
    appId: '1:119765972991:web:816387f5e377858b3b19ca',
    messagingSenderId: '119765972991',
    projectId: 'mafortune-ddf28',
    authDomain: 'mafortune-ddf28.firebaseapp.com',
    storageBucket: 'mafortune-ddf28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFEjeb82CjSzqKlFs-MBp3CswwvfXnuLM',
    appId: '1:119765972991:android:a6080758f3c3a0c93b19ca',
    messagingSenderId: '119765972991',
    projectId: 'mafortune-ddf28',
    storageBucket: 'mafortune-ddf28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-RR4E3uQBbj-amplcl5SHJeEYqFZzZdM',
    appId: '1:119765972991:ios:0380750a43693b043b19ca',
    messagingSenderId: '119765972991',
    projectId: 'mafortune-ddf28',
    storageBucket: 'mafortune-ddf28.firebasestorage.app',
    iosBundleId: 'com.example.mafortune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-RR4E3uQBbj-amplcl5SHJeEYqFZzZdM',
    appId: '1:119765972991:ios:0380750a43693b043b19ca',
    messagingSenderId: '119765972991',
    projectId: 'mafortune-ddf28',
    storageBucket: 'mafortune-ddf28.firebasestorage.app',
    iosBundleId: 'com.example.mafortune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Ek7LpvHhZTvMaYx4w5GZV1bNH6zsCZU',
    appId: '1:119765972991:web:7e0850b156d4e9ba3b19ca',
    messagingSenderId: '119765972991',
    projectId: 'mafortune-ddf28',
    authDomain: 'mafortune-ddf28.firebaseapp.com',
    storageBucket: 'mafortune-ddf28.firebasestorage.app',
  );
}
